import Image from "next/image";
import { ArrowDown, ArrowRight, MoveUpRight } from "lucide-react";

export function HeroSection() {
  return <section id="home" className="relative isolate flex min-h-screen items-center overflow-hidden bg-brand-primary">
    <Image src="https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=2200&q=90" alt="Turquoise alpine lake surrounded by dramatic mountains" fill priority sizes="100vw" placeholder="blur" blurDataURL="data:image/jpeg;base64,/9j/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAQUCf//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQMBAT8B/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQAGPwJ//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPyF//9oADAMBAAIAAwAAABAf/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPxB//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPxB//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxB//9k=" className="-z-20 object-cover object-center" />
    <div className="absolute inset-0 -z-10 bg-gradient-to-r from-brand-primary/90 via-brand-primary/55 to-brand-primary/5" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-brand-primary/65 via-transparent to-brand-primary/25" />
    <div className="container-site relative pb-16 pt-28 text-center md:text-left">
      <div className="mx-auto max-w-3xl md:mx-0"><span className="inline-flex items-center gap-2 rounded-full border border-brand-accent/35 bg-brand-accent/15 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-brand-accent">✦ &nbsp; Travel, a little more personally</span>
        <h1 className="mt-7 font-heading text-5xl font-semibold leading-[1.08] tracking-tight text-white sm:text-6xl lg:text-7xl">Go where the<br className="hidden sm:block" /> world <em className="font-normal text-brand-accent">opens up.</em></h1>
        <p className="mx-auto mt-6 max-w-xl text-base leading-7 text-white/80 sm:text-lg md:mx-0">Thoughtful journeys, shaped around you. Find the places that stay with you long after you return.</p>
        <div className="mt-8 flex flex-wrap justify-center gap-3 md:justify-start"><a href="#packages" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-brand-accent px-7 py-3 font-semibold text-brand-primary shadow-lg transition hover:brightness-105 active:scale-95">Find your journey <ArrowRight size={17} /></a><a href="#about" className="inline-flex min-h-12 items-center gap-2 rounded-full border-2 border-white/70 px-7 py-3 font-semibold text-white transition hover:bg-white hover:text-brand-primary">Our approach <MoveUpRight size={16} /></a></div>
        <div className="mt-12 flex flex-wrap items-center justify-center gap-x-8 gap-y-3 text-left md:justify-start"><div><p className="font-heading text-2xl font-semibold text-white">50<span className="text-brand-accent">+</span></p><p className="text-xs text-white/65">countries explored</p></div><span className="hidden h-9 w-px bg-white/30 sm:block"/><div><p className="font-heading text-2xl font-semibold text-white">12k<span className="text-brand-accent">+</span></p><p className="text-xs text-white/65">happy travellers</p></div><span className="hidden h-9 w-px bg-white/30 sm:block"/><div><p className="font-heading text-2xl font-semibold text-white">15</p><p className="text-xs text-white/65">years of getting lost</p></div></div>
      </div>
    </div>
    <a href="#about" aria-label="Scroll to our story" className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 flex-col items-center gap-2 text-xs uppercase tracking-widest text-white/70 md:flex"><span>Scroll to explore</span><ArrowDown size={16} className="animate-bounce" /></a>
    <div className="absolute bottom-7 right-7 hidden items-center gap-2 text-xs tracking-wider text-white/65 lg:flex"><span className="h-px w-8 bg-brand-accent"/> 46°28′N 13°48′E</div>
  </section>;
}
